name: "Binary Towers Security Audit"

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  devsecops_scan:
    name: "Web Audit (Semgrep OWASP)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Security Web Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/javascript
            p/typescript
            p/security-audit
            p/secrets
        continue-on-error: true
